# How to Neural Netowks Works with Simple Handwritten Example

#Import the libraries

In [70]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [71]:
(x_train, y_train), (x_test, y_test)=keras.datasets.mnist.load_data()

In [72]:
len(x_train)

60000

In [73]:
len(y_test)

10000

In [74]:
x_train[0].shape

(28, 28)

In [75]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [76]:
plt.matshow(x_train[1])

In [77]:
y_train[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

In [78]:
x_train=x_train/255

x_test=x_test/255

### Flatten means the two dimensional to one dimensional

In [79]:
x_train.shape

x_train_flattened = x_train.reshape(len(x_train), 28*28)

x_test_flattened = x_test.reshape(len(x_test), 28*28)


In [80]:
x_train_flattened.shape

(60000, 784)

In [81]:
x_train_flattened.shape

(60000, 784)

In [82]:
x_train_flattened[0]


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [83]:
model=keras.Sequential([
    keras.layers.Dense(10, input_shape=(784,), activation='sigmoid')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train_flattened, y_train, epochs=5)

Epoch 1/5


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8157 - loss: 0.7178
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9124 - loss: 0.3132
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9211 - loss: 0.2780
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9245 - loss: 0.2754
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9238 - loss: 0.2726


### check test accuracy

In [84]:
model.evaluate(x_test_flattened, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9154 - loss: 0.3044


[0.26815491914749146, 0.9244999885559082]

In [85]:
plt.matshow(x_test[0])

In [86]:
y_predict=model.predict(x_test_flattened)
y_predict[0]

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


array([2.09202170e-02, 3.55581847e-07, 3.54716443e-02, 9.67275321e-01,
       1.82203192e-03, 1.17750004e-01, 1.53242490e-06, 9.99750495e-01,
       9.08334851e-02, 5.63262343e-01], dtype=float32)

In [87]:
np.argmax(y_predict[0])

7

### create confusion martix

In [88]:
y_predicted_labels=[np.argmax(i) for i in y_predict]
y_predicted_labels[:5] 

[7, 2, 1, 0, 4]

In [89]:
cm=tf.math.confusion_matrix(labels=y_test, predictions=y_predicted_labels)

In [90]:
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 966,    0,    1,    2,    0,    4,    4,    2,    1,    0],
       [   0, 1112,    3,    2,    0,    1,    4,    2,   11,    0],
       [   7,    9,  921,   15,    7,    6,   11,   11,   42,    3],
       [   3,    0,   19,  930,    0,   22,    2,   10,   19,    5],
       [   2,    1,    6,    3,  910,    0,   10,    5,   11,   34],
       [  10,    3,    3,   38,    6,  782,   12,    4,   28,    6],
       [  14,    3,    5,    1,    7,   20,  904,    2,    2,    0],
       [   1,    7,   21,    8,    6,    0,    0,  949,    5,   31],
       [  10,    8,    7,   31,    9,   28,    8,   11,  856,    6],
       [  11,    7,    1,   12,   22,    9,    0,   24,    8,  915]])>

### create visualization

In [91]:
import seaborn as sns
plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel("Predicted")
plt.ylabel("truth")


Text(95.72222222222221, 0.5, 'truth')

### in last method error is big so add one hidden layer 

In [92]:
model1=keras.Sequential([
    keras.layers.Dense(100, input_shape=(784,), activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')  #add one hidden layer
])

model1.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model1.fit(x_train_flattened, y_train, epochs=5)

c:\Users\Muhammad Anique\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8731 - loss: 0.4512
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9594 - loss: 0.1385
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9738 - loss: 0.0910
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9796 - loss: 0.0682
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9848 - loss: 0.0536


In [93]:
model1.evaluate(x_test_flattened, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9715 - loss: 0.0904


[0.07769770920276642, 0.975600004196167]

In [94]:
y_predict = model1.predict(x_test_flattened)
y_predicted_labels=[np.argmax(i) for i in y_predict]
y_predicted_labels[:5] 

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


[7, 2, 1, 0, 4]

In [95]:
cm=tf.math.confusion_matrix(labels=y_test, predictions=y_predicted_labels)
plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel("Predicted")
plt.ylabel("truth")


Text(95.72222222222221, 0.5, 'truth')

### now the error is less so built in flatten layer so copy the previous code

In [96]:
model1=keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')  #add one hidden layer
])

model1.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model1.fit(x_train, y_train, epochs=5)

c:\Users\Muhammad Anique\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8653 - loss: 0.4701
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9591 - loss: 0.1395
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9726 - loss: 0.0904
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9808 - loss: 0.0660
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9836 - loss: 0.0524


In [97]:
model1.evaluate(x_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9657 - loss: 0.1169


[0.09944971650838852, 0.9700999855995178]

In [98]:
y_predict = model1.predict(x_test)
y_predicted_labels=[np.argmax(i) for i in y_predict]
y_predicted_labels[:5] 

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


[7, 2, 1, 0, 4]

In [99]:
cm=tf.math.confusion_matrix(labels=y_test, predictions=y_predicted_labels)
plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel("Predicted")
plt.ylabel("truth")


Text(95.72222222222221, 0.5, 'truth')

# Quantization

Quantization is a process of reducing model size so that it can run on EDGE Devices

## Types of Quantization
### 1. Post Training Quantization
    - This is the most common type of quantization. It occurs after the model is trained using a standard training algorithm.
    - Quantization involves rounding the weights and activations to a fixed number of bits, which can be 8-bit, 16-bit, or even 32-bit.
    - The smaller the quantized weights and activations, the smaller the model size.
    - Post-training quantization can be faster and more efficient than quantization during inference.

### 2. Quantization Aware Training
    - This type of quantization is used during the training process itself.
    - Quantization is applied to the weights and activations during the forward pass, and the resulting quantized values are used for the forward pass.
    - Quantization aware training can help improve the accuracy of the model while reducing the model size.
    - Quantization aware training can be more resource-intensive than post-training quantization, but it can also lead to better accuracy.



## post-training quantization

In [100]:
model=keras.models.load_model("handwritten_model.h5")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite=converter.convert()

INFO:tensorflow:Assets written to: C:\Users\MUHAMM~1\AppData\Local\Temp\tmp08a4w_ok\assets


INFO:tensorflow:Assets written to: C:\Users\MUHAMM~1\AppData\Local\Temp\tmp08a4w_ok\assets


Saved artifact at 'C:\Users\MUHAMM~1\AppData\Local\Temp\tmp08a4w_ok'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name='input_layer_2')
Output Type:
  TensorSpec(shape=(None, 10), dtype=tf.float32, name=None)
Captures:
  2467905719952: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2467905722832: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2467905721296: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2467905719376: TensorSpec(shape=(), dtype=tf.resource, name=None)


In [101]:
len(tflite)

319980

In [102]:
model=keras.models.load_model("handwritten_model.h5")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations=[tf.lite.Optimize.DEFAULT]
tflite_quant=converter.convert()

INFO:tensorflow:Assets written to: C:\Users\MUHAMM~1\AppData\Local\Temp\tmpljvq_saa\assets


INFO:tensorflow:Assets written to: C:\Users\MUHAMM~1\AppData\Local\Temp\tmpljvq_saa\assets


Saved artifact at 'C:\Users\MUHAMM~1\AppData\Local\Temp\tmpljvq_saa'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name='input_layer_2')
Output Type:
  TensorSpec(shape=(None, 10), dtype=tf.float32, name=None)
Captures:
  2468041220240: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2468041224848: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2468041224464: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2467905731856: TensorSpec(shape=(), dtype=tf.resource, name=None)


In [103]:
len(tflite_quant)

86040

In [104]:
with open("tflite_model.tflite", "wb") as f:
    f.write(tflite)

with open("tflite_quantize_model.tflite", "wb") as f:
    f.write(tflite_quant)


## Quantization Aware Training

In [105]:
import tensorflow_model_optimization as tfmop


In [106]:
model2=keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')  #add one hidden layer
])

#model1.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']

c:\Users\Muhammad Anique\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [107]:
import tensorflow_model_optimization as tfmop


In [110]:
import tensorflow as tf
#import tensorflow_model_optimization as tfmot

# 1. First verify TensorFlow and tfmot versions
print("TensorFlow version:", tf.__version__)
print("TF Model Optimization version:", tfmot.__version__)

# 2. Create a simple test model and explicitly check its type
model4 = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

# 3. Print model type
print("Model type:", type(model4))
print("Is Sequential:", isinstance(model1, tf.keras.Sequential))

# 4. Make sure model is built
model1.build(model1.input_shape)

# 5. Try quantization with error handling
try:
    quantize_model = tfmot.quantization.keras.quantize_model
    q_aware_model = quantize_model(model4)
    print("Quantization successful!")
except Exception as e:
    print("Quantization error:", str(e))

# 6. If successful, compile
if 'q_aware_model' in locals():
    q_aware_model.compile(optimizer='adam',
                         loss='sparse_categorical_crossentropy',
                         metrics=['accuracy'])
    print("Model compiled successfully!")

TensorFlow version: 2.18.0
TF Model Optimization version: 0.8.0
Model type: <class 'keras.src.models.sequential.Sequential'>
Is Sequential: True
Quantization error: `to_quantize` can only either be a keras Sequential or Functional model.


c:\Users\Muhammad Anique\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [125]:
import tensorflow as tf
import tensorflow_model_optimization as tfmot
# from tensorflow_model_optimization import tfmot
# Create model using tf.keras explicitly
model1 = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(28, 28)),  # Start with Input layer
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

# Verify model
print("Model type:", type(model1))
model1.summary()

# Try quantization
try:
    quantize_model = tfmot.quantization.keras.quantize_model(to_quantize, quantized_layer_name_prefix='quant_')   
    q_aware_model = quantize_model(model1)
    print("Quantization successful!")
    
    # Compile if successful
    q_aware_model.compile(optimizer='adam',
                         loss='sparse_categorical_crossentropy',
                         metrics=['accuracy'])
    print("Model compiled successfully!")
    q_aware_model.summary()
except Exception as e:
    print("Quantization error:", str(e))

Model type: <class 'keras.src.models.sequential.Sequential'>


Model: "sequential_19"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_13 (Flatten)            │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_36 (Dense)                │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_37 (Dense)                │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

Quantization error: name 'to_quantize' is not defined


In [121]:
import tensorflow as tf
import tensorflow_model_optimization as tfmot

print("TensorFlow version:", tf.__version__)
print("TF Model Optimization version:", tfmot.__version__)
print("Keras version:", tf.keras.__version__)

TensorFlow version: 2.18.0
TF Model Optimization version: 0.8.0
Keras version: 3.8.0
