# Martic Basics

### Matrix Subtraction

In [1]:
import numpy as np

revenues=np.array([[180, 200, 220],[24, 36, 40],[12,18,20]])
expenses=np.array([[80, 90, 100], [10, 16, 20], [8, 10,10]])

In [2]:
profit = revenues - expenses

print("Profit Matrix: \n", profit)

Profit Matrix: 
 [[100 110 120]
 [ 14  20  20]
 [  4   8  10]]


### Matrix Multiplication

In [6]:
price_per_unit=np.array([1000, 400, 1200])
units=np.array([[30, 40, 50], [5, 10, 15], [2, 5,7 ]])


In [7]:
prices=price_per_unit*units

print("Total Price Matrix: \n", prices)

Total Price Matrix: 
 [[30000 16000 60000]
 [ 5000  4000 18000]
 [ 2000  2000  8400]]


this not actual answer now use dot product 

In [8]:
update_price=np.dot(price_per_unit, units)
update_price

array([34400, 50000, 64400])