# Gradient Descent

### import libraries

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [6]:
df=pd.read_csv("D:\Machine Learning with python\deep learning course\deep learning practice\Practice_CSV_file\insurance_data.csv")
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\jk\AppData\Local\Temp\ipykernel_15760\3955155422.py:1: SyntaxWarning: invalid escape sequence '\M'
  df=pd.read_csv("D:\Machine Learning with python\deep learning course\deep learning practice\Practice_CSV_file\insurance_data.csv")


age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [9]:
from sklearn.model_selection import train_test_split

x=df[["age", "affordibility"]]
y=df["bought_insurance"]


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=25)

In [11]:
len(x_train)

22

### Scaling the "age" Column range [0,1] 

In [12]:
x_train_scaled=x_train.copy()

x_train_scaled["age"] = x_train_scaled["age"] / 100

x_test_scaled=x_test.copy()

x_test_scaled["age"] = x_test_scaled["age"] / 100

### build the model for single neural network

In [14]:
model= keras.Sequential([
    keras.layers.Dense(1, input_shape=[2], activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train_scaled, y_train, epochs=5000)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 960ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accurac

In [15]:
model.evaluate(x_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 555ms/step - accuracy: 1.0000 - loss: 0.3550


[0.3549776077270508, 1.0]

In [16]:
x_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [17]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step


array([[0.70548487],
       [0.3556957 ],
       [0.16827832],
       [0.47801185],
       [0.72606957],
       [0.8294983 ]], dtype=float32)

In [19]:
coef, intercept=model.get_weights()
coef, intercept

(array([[5.060863 ],
        [1.4086521]], dtype=float32),
 array([-2.913703], dtype=float32))

In [20]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [21]:
sigmoid(18)

np.float64(0.9999999847700205)

In [22]:
def prediction_function(age, affordabilties):
    weighted_sum=coef[0]*age +coef[1]*affordabilties +intercept
    return sigmoid(weighted_sum)

In [23]:
prediction_function(.47, 1)

array([0.7054848], dtype=float32)

### Implementation Gradient Descent form scratch

In [24]:
def log_loss(y_true, y_predicted):
    eplison=1e-15
    y_predicted_new=[max(i, eplison) for i in y_predicted]
    y_predicted_new= [min(i, 1-eplison) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [25]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12, 0, 1]))

array([0.99999386, 0.5       , 0.73105858])

In [26]:
def gradient_descent(age, affordability, y_true, epochs):
    w1=1.0
    w2=1.0
    b=0.0
    learning_rate=0.5
    n=len(age)
     
    for i in range(epochs):
        weighted_sum=w1*age + w2*affordability + b
        y_predicted=sigmoid_numpy(weighted_sum)
        
        loss=log_loss(y_true, y_predicted)
        
        w1d= (1/n)*np.dot(np.transpose(age), (y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordability), (y_predicted-y_true))   
        bias_d=np.mean(y_predicted-y_true)
        
        w1=w1- learning_rate*w1d 
        w2=w2- learning_rate*w2d
        
        print(f'Epoch: {i}, w1: {w1}, w2: {w2}, bias: {b}, loss: {loss}')
    return w1, w2, b


In [27]:
gradient_descent(x_train_scaled["age"], x_train_scaled["affordibility"], y_train, epochs=2000)

Epoch: 0, w1: 0.974907633470177, w2: 0.948348125394529, bias: 0.0, loss: 0.7113403233723417
Epoch: 1, w1: 0.951309050414721, w2: 0.8998384766138976, bias: 0.0, loss: 0.7049437880152859
Epoch: 2, w1: 0.9291619684235712, w2: 0.8543880770572044, bias: 0.0, loss: 0.6993052593238982
Epoch: 3, w1: 0.9084179079556838, w2: 0.8118995045564921, bias: 0.0, loss: 0.6943576384281475
Epoch: 4, w1: 0.8890233255496454, w2: 0.7722634615046652, bias: 0.0, loss: 0.6900349522584057
Epoch: 5, w1: 0.870920747167955, w2: 0.7353613402471417, bias: 0.0, loss: 0.6862734824669942
Epoch: 6, w1: 0.854049860257641, w2: 0.7010676910254683, bias: 0.0, loss: 0.6830126499196405
Epoch: 7, w1: 0.8383485325252197, w2: 0.6692525213982417, bias: 0.0, loss: 0.6801956585346196
Epoch: 8, w1: 0.8237537349858943, w2: 0.6397833777872467, bias: 0.0, loss: 0.6777699161231555
Epoch: 9, w1: 0.8102023557195147, w2: 0.6125271797757017, bias: 0.0, loss: 0.6756872590878301
Epoch: 10, w1: 0.7976318984134669, w2: 0.5873517948751835, bias: 

(np.float64(0.5737652257012215), np.float64(0.3445297964847951), 0.0)